export const mockData = [
    {
        id: 1,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Become a UI/UX Designer",
        habits: [
            {
                id: 1,
                title: "Habit 1",
                completed: false,
            },
            {
                id: 2,
                title: "Habit 2",
                completed: true,
            },
            {
                id: 3,
                title: "Habit 3",
                completed: true,
            },
        ],
        tasks: [
            {
                id: 1,
                title: "Task 1",
                completed: false,
            },
            {
                id: 2,
                title: "Task 2",
                completed: true,
            },
            {
                id: 3,
                title: "Task 3",
                completed: false,
            },
        ],
        dueDate: "2026-01-01",
        completed: false,
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Career & Development",
    },
    {
        id: 2,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Goal 2",
        habits: [
            {
                id: 1,
                title: "Habit 1",
                completed: true,
            },
            {
                id: 2,
                title: "Habit 2",
                completed: true,
            },
            {
                id: 3,
                title: "Habit 3",
                completed: true,
            },
        ],
        tasks: [
            {
                id: 1,
                title: "Task 1",
                completed: false,
            },
            {
                id: 2,
                title: "Task 2",
                completed: true,
            },
            {
                id: 3,
                title: "Task 3",
                completed: true,
            },
        ],
        dueDate: "2025-06-21",
        completed: true,
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Health",
    },
    {
        id: 3,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Lorem Ipsum Dolor Sit Amet Consectetur Adipiscing Elit Sed Do Eiusmod Tempor Incididunt Ut Labore Et Dolore Magna Aliqua",
        completed: false,
        habits: [],
        tasks: [],
        dueDate: "2025-06-21",
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Health",
    },
    {
        id: 4,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Learn How to Play Guitar",
        completed: false,
        habits: [],
        tasks: [],
        dueDate: "2025-06-21",
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Health",
    },
    {
        id: 5,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Learn How to Play Guitar",
        completed: false,
        habits: [],
        tasks: [],
        dueDate: "2025-06-21",
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Health",
    },
    {
        id: 6,
        createdAt: "2025-01-01",
        updatedAt: "2025-02-01",
        title: "Lorem Ipsum Dolor Sit Amet Consectetur Adipiscing Elit Sed Do Eiusmod Tempor Incididunt Ut Labore Et Dolore Magna Aliqua",
        completed: false,
        habits: [],
        tasks: [],
        dueDate: "2025-06-21",
        imageSmall: "https://picsum.photos/200/300",
        imageLarge: "https://picsum.photos/600/800",
        category: "Health",
    },
];